project:
  type: book
  preview:
    port: 3000
    browser: false

book:
  title: "Practical Deep Learning for Coders, 2nd Ed (Preview)"
  author: "Jeremy Howard and Sylvain Gugger"
  chapters:
    - index.qmd
    - intro.ipynb
      #- production.ipynb
    - book.qmd
      #- ethics.ipynb
    - book.qmd
    - mnist_basics.ipynb
      #- pet_breeds.ipynb
    - book.qmd
      #- multicat.ipynb
    - book.qmd
      #- sizing_and_tta.ipynb
    - book.qmd
      #- collab.ipynb
    - book.qmd
      #- tabular.ipynb
    - book.qmd
      #- nlp.ipynb
    - book.qmd
      #- midlevel_data.ipynb
    - book.qmd
      #- nlp_dive.ipynb
    - book.qmd
    - convolutions.ipynb
    - resnet.ipynb
      #- arch_details.ipynb
    - book.qmd
    - accel_sgd.ipynb
    - foundations.ipynb
      #- CAM.ipynb
      #- learner.ipynb
      #- conclusion.ipynb
  #appendices: 
    #- app_blog.ipynb
    #- app_jupyter.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo

