project:
  type: book
  preview:
    port: 3000
    browser: false

format:
  html:
    number-depth: 2
    theme: cosmo
    css: styles.css

book:
  title: "Practical Deep Learning for Coders"
  author: "Jeremy Howard and Sylvain Gugger"
  site-url: https://fastai.github.io/fastbook2e
  twitter-card:
    creator: "jeremyphoward"
    site: "fastdotai"
  open-graph: true
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
      - intro.ipynb
        #- production.ipynb
      - book2.qmd
        #- ethics.ipynb
      - book3.qmd
    - part: "The Details"
      chapters:
      - mnist_basics.ipynb
        #- pet_breeds.ipynb
      - book5.qmd
        #- multicat.ipynb
      - book6.qmd
        #- sizing_and_tta.ipynb
      - book7.qmd
        #- collab.ipynb
      - book8.qmd
        #- tabular.ipynb
      - book9.qmd
        #- nlp.ipynb
      - book10.qmd
    - part: "From the Foundations"
      chapters:
        #- midlevel_data.ipynb
      - book11.qmd
        #- nlp_dive.ipynb
      - book12.qmd
      - convolutions.ipynb
      - resnet.ipynb
        #- arch_details.ipynb
      - book15.qmd
      - accel_sgd.ipynb
      - foundations.ipynb
        #- CAM.ipynb
      - book18.qmd
        #- learner.ipynb
      - book19.qmd
        #- conclusion.ipynb
      - book20.qmd
    #appendices: 
      #- app_blog.ipynb
      #- app_jupyter.ipynb

bibliography: references.bib

